spring.application.name=Food-Delivery-Backend-Service
spring.datasource.url=jdbc:mysql://localhost:3306/foodapp
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect